/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package derbytrial;

/**
 *
 * @author Steven
 */
public class InfoEntry extends javax.swing.JFrame {

    /**
     * Creates new form InfoEntry
     */
    public InfoEntry() {
        initComponents();
    }

    // The code below sets up a check to make sure duplicate windows don't open.
    private static boolean isOpen = false;
    
    public static boolean getIsOpen(){
        return isOpen;
    }
    
    public static void setIsOpen(boolean set){
        isOpen = set;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        InfoTabs = new javax.swing.JTabbedPane();
        ArtistTab = new javax.swing.JPanel();
        ArtistNameLabel = new javax.swing.JLabel();
        ArtistNameField = new javax.swing.JTextField();
        AlbumTab = new javax.swing.JPanel();
        AlbumNameLabel = new javax.swing.JLabel();
        ArtistIDLabel = new javax.swing.JLabel();
        GenreLabel = new javax.swing.JLabel();
        ReleaseDateLabel = new javax.swing.JLabel();
        AlbumNameField = new javax.swing.JTextField();
        ArtistIDField = new javax.swing.JTextField();
        GenreField = new javax.swing.JTextField();
        ReleaseDateField = new javax.swing.JTextField();
        SongTab = new javax.swing.JPanel();
        SongNameLabel = new javax.swing.JLabel();
        AlbumIDLabel = new javax.swing.JLabel();
        SongNameField = new javax.swing.JTextField();
        AlbumIDField = new javax.swing.JTextField();
        StockTab = new javax.swing.JPanel();
        StockAlbumIDLabel = new javax.swing.JLabel();
        FormatLabel = new javax.swing.JLabel();
        StockVendorIDLabel = new javax.swing.JLabel();
        StockCostLabel = new javax.swing.JLabel();
        StockPriceLabel = new javax.swing.JLabel();
        StockAlbumIDField = new javax.swing.JTextField();
        FormatList = new javax.swing.JComboBox();
        StockVendorIDField = new javax.swing.JTextField();
        StockCostField = new javax.swing.JTextField();
        StockPriceField = new javax.swing.JTextField();
        VendorTab = new javax.swing.JPanel();
        VendorNameLabel = new javax.swing.JLabel();
        ContactNameLabel = new javax.swing.JLabel();
        ContactNumberLabel = new javax.swing.JLabel();
        VendorStreetLabel = new javax.swing.JLabel();
        VendorCityLabel = new javax.swing.JLabel();
        VendorStateLabel = new javax.swing.JLabel();
        VendorZIPLabel = new javax.swing.JLabel();
        VendorStateList = new javax.swing.JComboBox();
        VendorNameField = new javax.swing.JTextField();
        ContactNameField = new javax.swing.JTextField();
        ContactNumberField = new javax.swing.JTextField();
        VendorStreetField = new javax.swing.JTextField();
        VendorCityField = new javax.swing.JTextField();
        VendorZIPField = new javax.swing.JTextField();
        CustomerTab = new javax.swing.JPanel();
        CustomerNameLabel = new javax.swing.JLabel();
        PhoneNumberLabel = new javax.swing.JLabel();
        CustomerStreetLabel = new javax.swing.JLabel();
        CustomerCityLabel = new javax.swing.JLabel();
        CustomerStateLabel = new javax.swing.JLabel();
        CustomerZIPLabel = new javax.swing.JLabel();
        CustomerStateList = new javax.swing.JComboBox();
        CustomerNameField = new javax.swing.JTextField();
        PhoneNumberField = new javax.swing.JTextField();
        CustomerStreetField = new javax.swing.JTextField();
        CustomerCityField = new javax.swing.JTextField();
        CustomerZIPField = new javax.swing.JTextField();
        InfoEntryLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ArtistNameLabel.setText("Artist Name: ");

        javax.swing.GroupLayout ArtistTabLayout = new javax.swing.GroupLayout(ArtistTab);
        ArtistTab.setLayout(ArtistTabLayout);
        ArtistTabLayout.setHorizontalGroup(
            ArtistTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArtistTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ArtistNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ArtistNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
        ArtistTabLayout.setVerticalGroup(
            ArtistTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArtistTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArtistTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArtistNameLabel)
                    .addComponent(ArtistNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        InfoTabs.addTab("Artist", ArtistTab);

        AlbumNameLabel.setText("Album Name: ");

        ArtistIDLabel.setText("Artist ID:");

        GenreLabel.setText("Genre: ");

        ReleaseDateLabel.setText("Release Date:");

        javax.swing.GroupLayout AlbumTabLayout = new javax.swing.GroupLayout(AlbumTab);
        AlbumTab.setLayout(AlbumTabLayout);
        AlbumTabLayout.setHorizontalGroup(
            AlbumTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlbumTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlbumTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AlbumTabLayout.createSequentialGroup()
                        .addComponent(AlbumNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlbumNameField))
                    .addGroup(AlbumTabLayout.createSequentialGroup()
                        .addComponent(ReleaseDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReleaseDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .addGroup(AlbumTabLayout.createSequentialGroup()
                        .addComponent(ArtistIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ArtistIDField))
                    .addGroup(AlbumTabLayout.createSequentialGroup()
                        .addComponent(GenreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenreField)))
                .addContainerGap())
        );
        AlbumTabLayout.setVerticalGroup(
            AlbumTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlbumTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AlbumTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlbumNameLabel)
                    .addComponent(AlbumNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlbumTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArtistIDLabel)
                    .addComponent(ArtistIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlbumTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenreLabel)
                    .addComponent(GenreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AlbumTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReleaseDateLabel)
                    .addComponent(ReleaseDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        InfoTabs.addTab("Album", AlbumTab);

        SongNameLabel.setText("Song Name:");

        AlbumIDLabel.setText("Album ID:");

        javax.swing.GroupLayout SongTabLayout = new javax.swing.GroupLayout(SongTab);
        SongTab.setLayout(SongTabLayout);
        SongTabLayout.setHorizontalGroup(
            SongTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SongTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SongTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SongTabLayout.createSequentialGroup()
                        .addComponent(SongNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SongNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                    .addGroup(SongTabLayout.createSequentialGroup()
                        .addComponent(AlbumIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlbumIDField)))
                .addContainerGap())
        );
        SongTabLayout.setVerticalGroup(
            SongTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SongTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SongTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SongNameLabel)
                    .addComponent(SongNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SongTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlbumIDLabel)
                    .addComponent(AlbumIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        InfoTabs.addTab("Song", SongTab);

        StockAlbumIDLabel.setText("Album ID:");

        FormatLabel.setText("Format:");

        StockVendorIDLabel.setText("Vendor ID:");

        StockCostLabel.setText("Cost:");

        StockPriceLabel.setText("Sale Price:");

        FormatList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CD", "Cassette", "Vinyl" }));

        javax.swing.GroupLayout StockTabLayout = new javax.swing.GroupLayout(StockTab);
        StockTab.setLayout(StockTabLayout);
        StockTabLayout.setHorizontalGroup(
            StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StockTabLayout.createSequentialGroup()
                        .addComponent(StockAlbumIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockAlbumIDField))
                    .addGroup(StockTabLayout.createSequentialGroup()
                        .addComponent(FormatLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FormatList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 265, Short.MAX_VALUE))
                    .addGroup(StockTabLayout.createSequentialGroup()
                        .addComponent(StockVendorIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockVendorIDField))
                    .addGroup(StockTabLayout.createSequentialGroup()
                        .addComponent(StockCostLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockCostField))
                    .addGroup(StockTabLayout.createSequentialGroup()
                        .addComponent(StockPriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StockPriceField)))
                .addContainerGap())
        );
        StockTabLayout.setVerticalGroup(
            StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StockTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StockAlbumIDLabel)
                    .addComponent(StockAlbumIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormatLabel)
                    .addComponent(FormatList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StockVendorIDLabel)
                    .addComponent(StockVendorIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StockCostLabel)
                    .addComponent(StockCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StockPriceLabel)
                    .addComponent(StockPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        InfoTabs.addTab("Stock", StockTab);

        VendorNameLabel.setText("Vendor Name:");

        ContactNameLabel.setText("Contact Name:");

        ContactNumberLabel.setText("Contact Number:");

        VendorStreetLabel.setText("Street:");

        VendorCityLabel.setText("City:");

        VendorStateLabel.setText("State:");

        VendorZIPLabel.setText("ZIP:");

        VendorStateList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY" }));

        javax.swing.GroupLayout VendorTabLayout = new javax.swing.GroupLayout(VendorTab);
        VendorTab.setLayout(VendorTabLayout);
        VendorTabLayout.setHorizontalGroup(
            VendorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendorTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VendorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendorTabLayout.createSequentialGroup()
                        .addComponent(VendorNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VendorNameField))
                    .addGroup(VendorTabLayout.createSequentialGroup()
                        .addComponent(VendorStateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VendorStateList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(VendorTabLayout.createSequentialGroup()
                        .addComponent(ContactNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactNameField))
                    .addGroup(VendorTabLayout.createSequentialGroup()
                        .addComponent(ContactNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                    .addGroup(VendorTabLayout.createSequentialGroup()
                        .addComponent(VendorStreetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VendorStreetField))
                    .addGroup(VendorTabLayout.createSequentialGroup()
                        .addComponent(VendorCityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VendorCityField))
                    .addGroup(VendorTabLayout.createSequentialGroup()
                        .addComponent(VendorZIPLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VendorZIPField)))
                .addContainerGap())
        );
        VendorTabLayout.setVerticalGroup(
            VendorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendorTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VendorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VendorNameLabel)
                    .addComponent(VendorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VendorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactNameLabel)
                    .addComponent(ContactNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VendorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactNumberLabel)
                    .addComponent(ContactNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VendorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VendorStreetLabel)
                    .addComponent(VendorStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VendorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VendorCityLabel)
                    .addComponent(VendorCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VendorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VendorStateLabel)
                    .addComponent(VendorStateList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VendorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VendorZIPLabel)
                    .addComponent(VendorZIPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        InfoTabs.addTab("Vendor", VendorTab);

        CustomerNameLabel.setText("Name:");

        PhoneNumberLabel.setText("Phone Number:");

        CustomerStreetLabel.setText("Street:");

        CustomerCityLabel.setText("City:");

        CustomerStateLabel.setText("State:");

        CustomerZIPLabel.setText("ZIP:");

        CustomerStateList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY" }));

        javax.swing.GroupLayout CustomerTabLayout = new javax.swing.GroupLayout(CustomerTab);
        CustomerTab.setLayout(CustomerTabLayout);
        CustomerTabLayout.setHorizontalGroup(
            CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(CustomerNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerNameField))
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(PhoneNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhoneNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(CustomerStreetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerStreetField))
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(CustomerCityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerCityField))
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(CustomerStateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerStateList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CustomerTabLayout.createSequentialGroup()
                        .addComponent(CustomerZIPLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CustomerZIPField)))
                .addContainerGap())
        );
        CustomerTabLayout.setVerticalGroup(
            CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNameLabel)
                    .addComponent(CustomerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberLabel)
                    .addComponent(PhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerStreetLabel)
                    .addComponent(CustomerStreetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerCityLabel)
                    .addComponent(CustomerCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerStateLabel)
                    .addComponent(CustomerStateList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CustomerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerZIPLabel)
                    .addComponent(CustomerZIPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        InfoTabs.addTab("Customer", CustomerTab);

        InfoEntryLabel.setText("Information Entry");

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InfoTabs)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InfoEntryLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubmitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoEntryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        isOpen = false;
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        isOpen = false;
    }//GEN-LAST:event_formWindowClosing

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(InfoTabs.getSelectedIndex());
        switch (InfoTabs.getSelectedIndex()) {
            case 0:
                // get Artist field info and update
                break;
            case 1:
                // get Album info and update
                break;
            case 2:
                // get Song info and update
                break;
            case 3:
                // get Stock info and update
                break;
            case 4:
                // get Vendor info and update
                break;
            case 5:
                // get Customer info and update
                break;
            default: break;
        }
        
    }//GEN-LAST:event_SubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlbumIDField;
    private javax.swing.JLabel AlbumIDLabel;
    private javax.swing.JTextField AlbumNameField;
    private javax.swing.JLabel AlbumNameLabel;
    private javax.swing.JPanel AlbumTab;
    private javax.swing.JTextField ArtistIDField;
    private javax.swing.JLabel ArtistIDLabel;
    private javax.swing.JTextField ArtistNameField;
    private javax.swing.JLabel ArtistNameLabel;
    private javax.swing.JPanel ArtistTab;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField ContactNameField;
    private javax.swing.JLabel ContactNameLabel;
    private javax.swing.JTextField ContactNumberField;
    private javax.swing.JLabel ContactNumberLabel;
    private javax.swing.JTextField CustomerCityField;
    private javax.swing.JLabel CustomerCityLabel;
    private javax.swing.JTextField CustomerNameField;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JLabel CustomerStateLabel;
    private javax.swing.JComboBox CustomerStateList;
    private javax.swing.JTextField CustomerStreetField;
    private javax.swing.JLabel CustomerStreetLabel;
    private javax.swing.JPanel CustomerTab;
    private javax.swing.JTextField CustomerZIPField;
    private javax.swing.JLabel CustomerZIPLabel;
    private javax.swing.JLabel FormatLabel;
    private javax.swing.JComboBox FormatList;
    private javax.swing.JTextField GenreField;
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JLabel InfoEntryLabel;
    private javax.swing.JTabbedPane InfoTabs;
    private javax.swing.JTextField PhoneNumberField;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JTextField ReleaseDateField;
    private javax.swing.JLabel ReleaseDateLabel;
    private javax.swing.JTextField SongNameField;
    private javax.swing.JLabel SongNameLabel;
    private javax.swing.JPanel SongTab;
    private javax.swing.JTextField StockAlbumIDField;
    private javax.swing.JLabel StockAlbumIDLabel;
    private javax.swing.JTextField StockCostField;
    private javax.swing.JLabel StockCostLabel;
    private javax.swing.JTextField StockPriceField;
    private javax.swing.JLabel StockPriceLabel;
    private javax.swing.JPanel StockTab;
    private javax.swing.JTextField StockVendorIDField;
    private javax.swing.JLabel StockVendorIDLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField VendorCityField;
    private javax.swing.JLabel VendorCityLabel;
    private javax.swing.JTextField VendorNameField;
    private javax.swing.JLabel VendorNameLabel;
    private javax.swing.JLabel VendorStateLabel;
    private javax.swing.JComboBox VendorStateList;
    private javax.swing.JTextField VendorStreetField;
    private javax.swing.JLabel VendorStreetLabel;
    private javax.swing.JPanel VendorTab;
    private javax.swing.JTextField VendorZIPField;
    private javax.swing.JLabel VendorZIPLabel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
