/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package derbytrial;

/**
 *
 * @author Steven
 */
public class MasterMenu extends javax.swing.JFrame {

    /**
     * Creates new form MasterMenu
     */
    public MasterMenu() {
        initComponents();
    }
    
    // The code below sets up a check to make sure duplicate windows don't open.
    private static boolean isOpen = false;
    
    public static boolean getIsOpen(){
        return isOpen;
    }
    
    public static void setIsOpen(boolean set){
        isOpen = set;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MusicShopLabel = new javax.swing.JLabel();
        InfoEntryButton = new javax.swing.JButton();
        InfoViewButton = new javax.swing.JButton();
        POEntryButton = new javax.swing.JButton();
        SOEntryButton = new javax.swing.JButton();
        ReceivingButton = new javax.swing.JButton();
        OrderViewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MusicShopLabel.setText("Music Shop Menu");

        InfoEntryButton.setText("Info Entry");
        InfoEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoEntryButtonActionPerformed(evt);
            }
        });

        InfoViewButton.setText("Search");
        InfoViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoViewButtonActionPerformed(evt);
            }
        });

        POEntryButton.setText("Purchase Order Entry");
        POEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POEntryButtonActionPerformed(evt);
            }
        });

        SOEntryButton.setText("Sales Order Entry");
        SOEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SOEntryButtonActionPerformed(evt);
            }
        });

        ReceivingButton.setText("Receiving");
        ReceivingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceivingButtonActionPerformed(evt);
            }
        });

        OrderViewButton.setText("Order View");
        OrderViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderViewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MusicShopLabel)
                    .addComponent(POEntryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoEntryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SOEntryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReceivingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrderViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MusicShopLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoEntryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoViewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(POEntryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SOEntryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceivingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderViewButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoEntryButtonActionPerformed
        // TODO add your handling code here:
                
        if (InfoEntry.getIsOpen() == false) {
            InfoEntry.setIsOpen(true);
            InfoEntry IE = new InfoEntry();
            IE.setVisible(true);
        }
    }//GEN-LAST:event_InfoEntryButtonActionPerformed

    private void InfoViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoViewButtonActionPerformed
        // TODO add your handling code here:
        if (SearchWindow.getIsOpen() == false) {
            SearchWindow.setIsOpen(true);
            SearchWindow IV = new SearchWindow();
            IV.setVisible(true);
        }
    }//GEN-LAST:event_InfoViewButtonActionPerformed

    private void POEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POEntryButtonActionPerformed
        // TODO add your handling code here:
        if (PurchaseOrderEntry.getIsOpen()==false){
            PurchaseOrderEntry.setIsOpen(true);
            PurchaseOrderEntry POE = new PurchaseOrderEntry();
            POE.setVisible(true);
        }
    }//GEN-LAST:event_POEntryButtonActionPerformed

    private void SOEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SOEntryButtonActionPerformed
        // TODO add your handling code here:
        if (SalesOrderEntry.getIsOpen()==false){
            SalesOrderEntry.setIsOpen(true);
            SalesOrderEntry SOE = new SalesOrderEntry();
            SOE.setVisible(true);
        }
    }//GEN-LAST:event_SOEntryButtonActionPerformed

    private void ReceivingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceivingButtonActionPerformed
        // TODO add your handling code here:
        if (Receiving.getIsOpen()==false){
            Receiving.setIsOpen(true);
            Receiving R = new Receiving();
            R.setVisible(true);
        }
    }//GEN-LAST:event_ReceivingButtonActionPerformed

    private void OrderViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderViewButtonActionPerformed
        // TODO add your handling code here:
        if (TransactionView.getIsOpen()==false){
            TransactionView.setIsOpen(true);
            TransactionView TV = new TransactionView();
            TV.setVisible(true);
        }
    }//GEN-LAST:event_OrderViewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfoEntryButton;
    private javax.swing.JButton InfoViewButton;
    private javax.swing.JLabel MusicShopLabel;
    private javax.swing.JButton OrderViewButton;
    private javax.swing.JButton POEntryButton;
    private javax.swing.JButton ReceivingButton;
    private javax.swing.JButton SOEntryButton;
    // End of variables declaration//GEN-END:variables
}
